### ISSUE TITLE
Update inquire to v0.5.2

### ISSUE THREAD

**Issue by mikaelmello** [EricCrosson/git-disjoint#119]
Hey! Maintainer of the inquire crate here.

I pushed a silly regression on versions 0.5.0 and 0.5.1 and doing some Github search saw that you recently upgraded to one of these two.

The regression is a capitalization typo: `THe` instead of `The` in the default error message when the password confirmation does not match the main input.

Just a heads-up in case you're currently affected or might be in a future where you use Password prompts!

**Comment by EricCrosson** [comment]
Closed in https://github.com/EricCrosson/git-disjoint/pull/120
