### ISSUE TITLE
Add progress bar for opening PR

### ISSUE THREAD

**Issue by ericcrosson-bitgo** [EricCrosson/git-disjoint#204]
Since PR creation is so synchronous and slow, it would be less jarring for the user to describe what's happening during that lag.

**Comment by ericcrosson-bitgo** [comment]
How does this relate to #201?

**Comment by EricCrosson** [comment]
Now that the PR is opened in the background, I don't think this is as useful.

Additionally, the output of git-disjoint is currently high level: mapping issue groups to commits, and does not describe low level work like creating branches, or even branch names. I'm not sure yet if it's best to keep it that way but the current UI has no room for this information.
